#!/usr/bin/env python3
"""
execute_download_reorganize.py
Safely executes the reorganization plan for /mnt/hdd-backup/download/ generated by analyze_download_metadata.py.
Features:
  - Atomic moves (shutil.move)
  - Windows SMB character sanitization check
  - Permissions enforcement (100000:100000, 775/664)
  - Prunes empty obsolete artist/dummy directories
  - Logging to /tmp/reorganize_exec.log
"""

import os
import sys
import json
import shutil
from pathlib import Path

PLAN_FILE = "/tmp/download_reorganize_plan.json"
LOG_FILE = "/tmp/reorganize_exec.log"
BASE_DIR = "/mnt/hdd-backup/download"

def log(msg):
    print(msg)
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(msg + "\n")

def apply_permissions(path):
    try:
        # 100000:100000
        os.chown(path, 100000, 100000)
    except Exception:
        pass
    try:
        if os.path.isdir(path):
            os.chmod(path, 0o775)
        else:
            os.chmod(path, 0o664)
    except Exception:
        pass

def recursive_apply_permissions(root_path):
    for root, dirs, files in os.walk(root_path):
        apply_permissions(root)
        for f in files:
            apply_permissions(os.path.join(root, f))

def prune_empty_dirs(root_dir):
    log("Pruning empty obsolete directories...")
    pruned_count = 0
    for root, dirs, files in os.walk(root_dir, topdown=False):
        if root == root_dir:
            continue
        try:
            if not os.listdir(root):
                os.rmdir(root)
                pruned_count += 1
        except Exception:
            pass
    log(f"Pruned {pruned_count} empty directories.")

def main():
    if not os.path.exists(PLAN_FILE):
        log(f"Error: Plan file {PLAN_FILE} not found!")
        sys.exit(1)

    with open(PLAN_FILE, "r", encoding="utf-8") as f:
        plan = json.load(f)

    log(f"=== Starting Download Reorganization Execution ===")
    log(f"Total albums to process: {len(plan)}")

    success_count = 0
    skip_count = 0
    fail_count = 0

    for idx, item in enumerate(plan, 1):
        src = item["source"]
        dst = item["target"]

        if not os.path.exists(src):
            # Already moved or does not exist
            skip_count += 1
            continue

        if os.path.abspath(src) == os.path.abspath(dst):
            skip_count += 1
            continue

        try:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            apply_permissions(os.path.dirname(dst))

            # Move directory
            shutil.move(src, dst)
            recursive_apply_permissions(dst)
            success_count += 1
            if success_count % 50 == 0 or success_count == len(plan):
                log(f"Progress: [{idx}/{len(plan)}] Moved {success_count} albums successfully...")
        except Exception as e:
            fail_count += 1
            log(f"FAIL: {src} -> {dst} | Error: {e}")

    log(f"\nExecution Summary:")
    log(f"  - Successfully moved: {success_count}")
    log(f"  - Skipped (identical/missing): {skip_count}")
    log(f"  - Failed: {fail_count}")

    prune_empty_dirs(BASE_DIR)
    log("=== Download Reorganization Execution Completed ===")

if __name__ == "__main__":
    main()
