services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - shared_net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - radarr_config:/config
      - /mnt/hdd-media:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - shared_net

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - sonarr_config:/config
      - /mnt/hdd-media:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - shared_net

volumes:
  prowlarr_config:
  radarr_config:
  sonarr_config:

networks:
  shared_net:
    external: true
