services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    volumes:
    - /mnt/hdd-media/manga-reader:/data
    - komga_config:/config
    ports:
    - 25600:25600
    environment:
    - TZ=Asia/Jakarta
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_CLIENT-ID=komga-oidc-sso
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_CLIENT-SECRET=bae1553afa7f3218b32ee7485f4c91e5246121227abed531
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_CLIENT-NAME=Homelab IDP
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_SCOPE=openid,profile,email
    - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_HOMELAB-IDP_ISSUER-URI=http://192.168.18.225:8300
    networks:
    - shared_net
volumes:
  komga_config: null
networks:
  shared_net:
    external: true
