services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    volumes:
    - /mnt/hdd-media/manga-reader:/data
    - komga_config:/config
    ports:
    - 25600:25600
    environment:
    - TZ=Asia/Jakarta
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_CLIENT-ID=komga-oidc-sso
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_CLIENT-SECRET=7450659b80ab03a18de85e698c8770eeaeed39c227e34c56
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_CLIENT-NAME=Homelab IDP
    - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_HOMELAB-IDP_SCOPE=openid,profile,email
    - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_HOMELAB-IDP_ISSUER-URI=https://sso.suryatmaja.dev
    networks:
    - shared_net
volumes:
  komga_config: null
networks:
  shared_net:
    external: true
