services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 0:0
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_ENABLETRANSCODINGCONFIG: 'false'
      ND_BASEURL: ''
      ND_REVERSEPROXYUSERHEADER: Remote-User
      ND_REVERSEPROXYWHITELIST: 0.0.0.0/0
    volumes:
    - navidrome_data:/data
    - /mnt/hdd-music/music:/music:ro
    networks:
    - shared_net
  navidrome-proxy:
    image: nginx:alpine
    container_name: navidrome-proxy
    restart: unless-stopped
    ports:
    - 4533:80
    volumes:
    - ./sso-sidecars/navidrome.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - navidrome
    networks:
    - shared_net
volumes:
  navidrome_data: null
networks:
  shared_net:
    external: true
