services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 0:0 # root or matched UID
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: Put your configuration options here. See https://www.navidrome.org/docs/usage/configuration-options/#available-options
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_ENABLETRANSCODINGCONFIG: "false"
      ND_BASEURL: ""
    volumes:
      - navidrome_data:/data
      - /mnt/hdd-music/music:/music:ro
    networks:
      - shared_net

volumes:
  navidrome_data:

networks:
  shared_net:
    external: true
