services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - SUBFOLDER=/ #optional
      - TITLE=Kasm Webtop #optional
    volumes:
      - webtop_config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3001:3000
      - 3002:3001
    restart: unless-stopped
    networks:
      - shared_net

volumes:
  webtop_config:

networks:
  shared_net:
    external: true
