server {
    listen 80;
    
    # Forward Auth Verification
    location /npm-auth-verify {
        internal;
        proxy_pass http://homelab-idp:4000/api/auth/verify;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }

    location / {
        auth_request /npm-auth-verify;

        auth_request_set $remote_user $upstream_http_remote_user;
        auth_request_set $remote_email $upstream_http_remote_email;
        auth_request_set $remote_name $upstream_http_remote_name;

        proxy_set_header Remote-User $remote_user;
        proxy_set_header Remote-Email $remote_email;
        proxy_set_header Remote-Name $remote_name;

        error_page 401 = @error401;
        proxy_pass http://navidrome:4533;
        
        # WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        
    }

    location @error401 {
        return 302 https://sso.suryatmaja.dev/login?rd=$scheme://$http_host$request_uri;
    }
}
